apiVersion: v2
name: trading
description: A Helm chart for an algorithmic trading system
type: application
version: 2.0.25
appVersion: 1.8.2
dependencies:
  - name: influxdb
    version: 2.2.7
    repository: https://charts.bitnami.com/bitnami
  - name: purple_trader
    version: 1.0.5
    repository: file://../purple_trader
  - name: blue_trader
    version: 1.0.5
    repository: file://../blue_trader
  - name: ingestion
    version: 0.3.0
    repository: file://../ingestion
