influxdb:
    influxdb: # false flag
        resources:
            requests:
                cpu: 1730m
                memory: 4776Mi
    auth:
        enabled: true
        createUserToken: true
        admin:
            username: admin
            password: password
            org: quant
            bucket: trading
            token: I2aip61c5iYqaTcXJvvV


ingestion:
    influxDBSecret: trading-ingestion-influx-secret
    image:
        repository: 565925249289.dkr.ecr.us-east-1.amazonaws.com/trade-ingestion
        pullPolicy: Always
        # Overrides the image tag whose default is the chart appVersion.
        tag: "1.8.1"

purple_trader:
    nameOverride: "purple-trader"
    serviceAccount:
        create: true
        name: "purple-trader"
    coinbaseCredSecret: purple-trader-coinbase-creds
    influxDBSecret: trading-trader-influx-secret
    image:
        repository: 565925249289.dkr.ecr.us-east-1.amazonaws.com/trader
        pullPolicy: Always
        # Overrides the image tag whose default is the chart appVersion.
        tag: "1.8.1"
    extraEnv:
        MR_EMA_PERIODS: "20"
        MR_BUY_FRACTION: "0.5"
        MR_SELL_FRACTION: "0.9"


blue_trader:
    nameOverride: "blue-trader"
    serviceAccount:
        create: true
        name: "blue-trader"
    coinbaseCredSecret: blue-trader-coinbase-creds
    influxDBSecret: trading-trader-influx-secret
    image:
        repository: 565925249289.dkr.ecr.us-east-1.amazonaws.com/trader
        pullPolicy: Always
        # Overrides the image tag whose default is the chart appVersion.
        tag: "1.8.1"
    extraEnv:
        MR_EMA_PERIODS: "20"
        MR_BUY_FRACTION: "0.5"
        MR_SELL_FRACTION: "0.9"
