influxdb:
    influxdb:
        resources:
            requests:
                cpu: 1730m
                memory: 4776Mi
    auth:
        enabled: true
        createUserToken: true
        admin:
            username: admin
            password: password
            org: quant
            bucket: trading
            token: I2aip61c5iYqaTcXJvvV


ingestion:
    influxDBSecret: trading-ingestion-influx-secret
    image:
        repository: 565925249289.dkr.ecr.us-east-1.amazonaws.com/trade-ingestion
        pullPolicy: Always
        # Overrides the image tag whose default is the chart appVersion.
        tag: "2.0.2"

purple_trader:
    nameOverride: "purple-trader"
    serviceAccount:
        create: true
        name: "purple-trader"
    coinbaseCredSecret: purple-trader-coinbase-creds
    influxDBSecret: trading-trader-influx-secret
    image:
        repository: 565925249289.dkr.ecr.us-east-1.amazonaws.com/trader
        pullPolicy: Always
        tag: "2.0.2"
    extraEnv:
        MR_EMA_PERIODS: "30"
        MR_BUY_FRACTION: "0.5"
        MR_SELL_FRACTION: "0.888"
        STOP_LOSS: "0.98"
        COOLDOWN_SECONDS: 10800
        BUY_TARGET_SECONDS: 360
        SELL_TARGET_SECONDS: 360

blue_trader:
    nameOverride: "blue-trader"
    serviceAccount:
        create: true
        name: "blue-trader"
    coinbaseCredSecret: blue-trader-coinbase-creds
    influxDBSecret: trading-trader-influx-secret
    image:
        repository: 565925249289.dkr.ecr.us-east-1.amazonaws.com/trader
        pullPolicy: Always
        tag: "2.0.2"
    extraEnv:
        MR_EMA_PERIODS: "26"
        MR_BUY_FRACTION: "0.5"
        MR_SELL_FRACTION: "0.888"
        STOP_LOSS: "0.98"
        COOLDOWN_SECONDS: 10800
        BUY_TARGET_SECONDS: 300
        SELL_TARGET_SECONDS: 300

red_trader:
    nameOverride: "red-trader"
    serviceAccount:
        create: true
        name: "red-trader"
    coinbaseCredSecret: red-trader-coinbase-creds
    influxDBSecret: trading-trader-influx-secret
    image:
        repository: 565925249289.dkr.ecr.us-east-1.amazonaws.com/trader
        pullPolicy: Always
        tag: "2.0.2"
    extraEnv:
        MR_EMA_PERIODS: "34"
        MR_BUY_FRACTION: "0.5"
        MR_SELL_FRACTION: "0.888"
        STOP_LOSS: "0.98"
        COOLDOWN_SECONDS: 10800
        BUY_TARGET_SECONDS: 300
        SELL_TARGET_SECONDS: 300
