influxdb:
    influxdb:
        resources:
            requests:
                cpu: 1730m
                memory: 4776Mi
    auth:
        enabled: true
        createUserToken: true
        admin:
            username: admin
            password: password
            org: quant
            bucket: trading
            token: I2aip61c5iYqaTcXJvvV


ingestion:
    influxDBSecret: trading-ingestion-influx-secret
    image:
        repository: 565925249289.dkr.ecr.us-east-1.amazonaws.com/trade-ingestion
        pullPolicy: Always
        # Overrides the image tag whose default is the chart appVersion.
        tag: "1.8.13"

purple_trader:
    nameOverride: "purple-trader"
    serviceAccount:
        create: true
        name: "purple-trader"
    coinbaseCredSecret: purple-trader-coinbase-creds
    influxDBSecret: trading-trader-influx-secret
    image:
        repository: 565925249289.dkr.ecr.us-east-1.amazonaws.com/trader
        pullPolicy: Always
        tag: "1.8.13"
    extraEnv:
        MR_EMA_PERIODS: "20"
        MR_BUY_FRACTION: "0.5"
        MR_SELL_FRACTION: "0.875"
        MR_BUY_THRESHOLD: "0.001"
        MR_SELL_THRESHOLD: "0.001"
        STOP_LOSS: "0.99"
        COOLDOWN_SECONDS: 2700
        BUY_TARGET_SECONDS: 180
        SELL_TARGET_SECONDS: 180

blue_trader:
    nameOverride: "blue-trader"
    serviceAccount:
        create: true
        name: "blue-trader"
    coinbaseCredSecret: blue-trader-coinbase-creds
    influxDBSecret: trading-trader-influx-secret
    image:
        repository: 565925249289.dkr.ecr.us-east-1.amazonaws.com/trader
        pullPolicy: Always
        tag: "1.8.13"
    extraEnv:
        MR_EMA_PERIODS: "26"
        MR_BUY_FRACTION: "0.5"
        MR_SELL_FRACTION: "0.875"
        MR_BUY_THRESHOLD: "0.001"
        MR_SELL_THRESHOLD: "0.001"
        STOP_LOSS: "0.99"
        COOLDOWN_SECONDS: 3600
        BUY_TARGET_SECONDS: 300
        SELL_TARGET_SECONDS: 300

red_trader:
    extraEnv:
        MR_EMA_PERIODS: "36"
        MR_BUY_FRACTION: "0.5"
        MR_SELL_FRACTION: "0.875"
        MR_BUY_THRESHOLD: "0.001"
        MR_SELL_THRESHOLD: "0.001"
        STOP_LOSS: "0.99"
        COOLDOWN_SECONDS: 7200
        BUY_TARGET_SECONDS: 600
        SELL_TARGET_SECONDS: 600
    nameOverride: "red-trader"
    serviceAccount:
        create: true
        name: "red-trader"
    coinbaseCredSecret: red-trader-coinbase-creds
    influxDBSecret: trading-trader-influx-secret
    image:
        repository: 565925249289.dkr.ecr.us-east-1.amazonaws.com/trader
        pullPolicy: Always
        tag: "1.8.13"
