{{- define "libtrader.serviceaccount.tpl" -}}
  {{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "blue_trader.serviceAccountName" . }}
  labels:
  {{- include "blue_trader.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- end -}}