{{- define "libtrader.serviceaccount" -}}
  {{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "libtrader.serviceAccountName" . }}
  labels:
  {{- include "libtrader.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- end -}}