apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingestion.influxDBSecret }}
  labels:
    app: {{ template "trading.fullname" . }}
    chart: {{ template "trading.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  INFLUX_URL: {{ printf "http://trading-influxdb.trading.svc.cluster.local:8086" | b64enc | quote }}
  INFLUX_ORG: {{ printf "quant" | b64enc | quote }}
  INFLUX_ORG_ID: {{ printf "e0f06e8befbb9f22" | b64enc | quote }}
  INFLUX_USER: {{ printf "tradeingestion" | b64enc | quote }}
  INFLUX_TOKEN: {{ printf "JeAd3Xw3-Cs1S7C1h2aqsk-adjbtB8y7FrPa_eR6zuQ8MR8CVzm-OxdBKj6qhZE3F0YiSYaCDiCinJdYGya9PQ==" | b64enc | quote }}

