apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingestion.influxDBSecret }}
  labels:
    app: {{ template "trading.fullname" . }}
    chart: {{ template "trading.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  INFLUX_URL: {{ printf "http://trading-influxdb.trading.svc.cluster.local:8086" | b64enc | quote }}
  INFLUX_ORG: {{ printf "quant" | b64enc | quote }}
  INFLUX_ORG_ID: {{ printf "8f644d35d8d8e0ed" | b64enc | quote }}
  INFLUX_USER: {{ printf "ingestion" | b64enc | quote }}
  INFLUX_TOKEN: {{ printf "WW065QIqXJA-8AjfHzNJtAZuD9TXZH5ugqrYtlhjJaR99m0yovXrWwFzXKzzj6m7_PM4Ay2u-vh64TknFRl3KQ==" | b64enc | quote }}