apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.trader.influxDBSecret }}
  labels:
    app: {{ template "trading.fullname" . }}
    chart: {{ template "trading.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
    INFLUX_URL: {{ printf "http://trading-influxdb.trading.svc.cluster.local:8086" | b64enc | quote }}
    INFLUX_ORG: {{ printf "quant" | b64enc | quote }}
    INFLUX_ORG_ID: {{ printf "e0f06e8befbb9f22" | b64enc | quote }}
    INFLUX_USER: {{ printf "trader" | b64enc | quote }}
    INFLUX_TOKEN: {{ printf "cnyETE2s0IrWWK5MdqgQqZp_iWgq2vjVkeNHyG2MjzZsLXUS0OG-p4zgpQ0GNaDQ_rV-6UePXJRJRbjN8C6pBw==" | b64enc | quote }}
