apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.trader.influxDBSecret }}
  labels:
    app: {{ template "trading.fullname" . }}
    chart: {{ template "trading.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  INFLUX_URL: {{ printf "http://trading-influxdb.trading.svc.cluster.local:8086" | b64enc | quote }}
  INFLUX_ORG: {{ printf "quant" | b64enc | quote }}
  INFLUX_ORG_ID: {{ printf "8f644d35d8d8e0ed" | b64enc | quote }}
  INFLUX_USER: {{ printf "trader" | b64enc | quote }}
  INFLUX_TOKEN: {{ printf "5_jk-JFkqGFx-YnCnpx77TKuJvsaeODQIIuMQQxYjYBbwwpJbn9Ta4-XPN1pFoXzGvsESPlCgCbMxctmQPY5cQ==" | b64enc | quote }}
